### ISSUE TITLE
Déployer l'action sur le Market place

### ISSUE THREAD

**Issue by mbarre** [opt-nc/tower-deploy-action#1]
- [x] Mettre a jour le README
- [x] Mettre la repo en public
- [x] Tester avec consumer-sirh

**Comment by mbarre** [comment]
https://github.com/marketplace/actions/deploy-with-tower-ansible

**Comment by adriens** [comment]
Release et première publicatoin effectuée : 

![image](https://user-images.githubusercontent.com/5235127/146309222-6f008659-2bb8-4612-b363-22910174d904.png)

**Comment by mbarre** [comment]
![image](https://user-images.githubusercontent.com/1823161/146310482-70d65926-8b09-4ed8-a9a9-93e9d776ab2b.png)

**Comment by adriens** [comment]
Et encore bravo 👏
