### ISSUE TITLE
GitHub Action prend parfois `3x` le temps Tower ❔

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/tower-deploy-action#11]
## Exemple : `mobitag-loader` _(jar de ~5mo)_ : 

- Pour [55s de la GH Action](https://github.com/opt-nc/mobitag-loader/runs/7920350153?check_suite_focus=true)

![image](https://user-images.githubusercontent.com/39691264/185646247-9d0c2039-5b84-49c2-b8b2-d2798423aba0.png)

- [18s](https://tower.intranet.opt/#/jobs/playbook/168989?job_search=page_size:20;order_by:-finished;not__launch_type:sync) selon Tower 😳

![image](https://user-images.githubusercontent.com/39691264/185646386-292ec7a5-e218-42e0-b01a-d43c59003f22.png)

👉🏼 Gain de qualité de travail 😊 et de réduction des temps GitHub à la clé💰

**Comment by Dougniel** [comment]
## ☝️ Le temps affiché dans Tower comprends uniquement le temps d'exécution sans le temps en _pending_ 

![image](https://user-images.githubusercontent.com/39691264/185661532-61ed9eb1-8aab-4ef7-a952-f1cadd02a7e7.png)

Dans cet exemple pour un temps GitHub de `55s` : 
- `30s` de _pending_ Tower 🤑
- `20s` d'exécution effective ⚙️
- `5s` de latence liée au mécanisme de qui scrute le status du job Tower 🤷

ℹ️ Au passage, sur le même sujet et pour rappel, on a aussi le ticket d'entrée Docker sur GH Action : 

<img width="607" alt="image" src="https://user-images.githubusercontent.com/39691264/185663054-9d9eb9da-bd1e-45b7-8cfe-3d5d57ab6998.png">

@adriens, tu pourrais te rapprocher de David pour comprendre pourquoi ce _pending_ est si long ? il y a un gain 💰important il me semble

Le problème ne viens pas de la lib alors je clôture, mais je livre tout de même la modif avec les timestamps dans les logs

**Comment by adriens** [comment]
> [@adriens](https://github.com/adriens), tu pourrais te rapprocher de David pour comprendre pourquoi ce pending est si long ? il y a un gain 💰important il me semble

Yes, je vais m'y atteler.

> Le problème ne viens pas de la lib alors je clôture, mais je livre tout de même la modif avec les timestamps dans les logs.

:point_up: Du coup on ne réfélchit plus au portage de Docker/Python vers js pour la GH Action :grey_question:

**Comment by adriens** [comment]
> on a aussi le ticket d'entrée Docker sur GH Action

Peux-tu le créer stp et le linker à celui-ci ?
