### ISSUE TITLE
Portage Docker/Python vers js pour la GH Action ⏱

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/tower-deploy-action#13]
> on a aussi le ticket d'entrée Docker sur GH Action

Peux-tu le créer stp et le linker à celui-ci ?

_Originally posted by @adriens in https://github.com/opt-nc/tower-deploy-action/issues/11#issuecomment-1221116776_

- `15s` est le temps que met cette GitHub action pour le Setup à chaque exécution et ça semble être liée au fait que ce soit une image Docker
- Ce temps peut faire basculer une exécution à la minute de facturation GitHub supérieur 💰

**Comment by Dougniel** [comment]
@adriens, j'ai mon todo un peu vide (et ça risque de rester un peu vu que tu n'es pas là la semaine pro) et pas mal en pending, je peux passer sur ce ticket ? Sauf si tu vois d'autres priorités

**Comment by adriens** [comment]
Yes, of course, profite-en. Il faudra par-contre s'occupper de https://github.com/opt-nc/GLIA/issues/849 :pray:  :sweat: ... mais en mocde super clean avec `picocli`

**Comment by adriens** [comment]
Issue pinée

![image](https://user-images.githubusercontent.com/5235127/198406084-d9f2aaf5-253c-4178-b5d3-2de9f6cecf14.png)

**Comment by Dougniel** [comment]
Voilà `12-14s` en moins à chaque lancement 💰:

<img width="917" alt="image" src="https://user-images.githubusercontent.com/39691264/200339258-08619ff3-c70a-44d9-9d5c-c7b1446207f6.png">

Par rapport à avant : 
![image](https://user-images.githubusercontent.com/39691264/200339993-398784b3-cfa0-472b-b947-09d876fca793.png)

**Comment by adriens** [comment]
> Voilà 12-14s en moins à chaque lancement 💰:

C'est énorme, ça c'est du ROI :clap: 

Tu penses que tu aurais quelques RUNs sur différents projets avec des temps pour moi stp ?

**Comment by adriens** [comment]
(Je souhaite faire une annonce pour cette release, avec quelques chiffres remarqsuables)

**Comment by Dougniel** [comment]
> > Voilà 12-14s en moins à chaque lancement 💰:
> 
> C'est énorme, ça c'est du ROI 👏
> 
> Tu penses que tu aurais quelques RUNs sur différents projets avec des temps pour moi stp ?

- [Pour le plus avancé c'est proxy-docubase](https://github.com/opt-nc/proxy-docubase/actions/runs/3409833725) à mon sens car on déploie une image Docker, par contre on est pénalisé sur la génération native : `5m42` (build natif) + `42s` de déploiement donc `6m24` au total _(en non natif on descendrait à un build de < `50s` donc point un total <`1m40`)_: 

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/39691264/200475524-f4076207-0e4d-4ccc-824c-4bb310df965f.png">

- Pour un cas représentatif c'est Pyramide parce qu'il est fait JHipster, il fait pas au porte monnaie car à lui seul il coûte `14m` 💰, en termes d'attente cela représente `7m30` 😅 au total (build SB / build Angluar - sans la dernière version de `tower-deploy-action`) : 
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/39691264/200478228-43b0910b-d238-48f9-a29f-25247bf854da.png">

- Pour un type d'application consumer (ex: [consumer-sig](https://github.com/opt-nc/consumer-sig/actions/runs/3248195753), c'est pas le plus lent) on arrive à un temps de build déploiement à `2m52` au total _(ce qui reste important mais sans la dernière version de `tower-deploy-action`: -14s et sans une gestion du cache des dépendances maven efficace comme ce qui a été fait pour proxy-docubase dernièrement avec une version statique)_
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/39691264/200479341-3f023f5a-8d00-4413-af9f-4f14c069a49f.png">


☝️une partie non négligeable du temps de déploiement est liée à un état d'attente de Tower "pending" (j'avais déjà signalé) avant le lancement, si ce temps pouvait être supprimé on économiserai du temps et de l'argent 💰_(ex: pour un total de déploiement Tower sur l'exemple du proxy-docubase de `42s` env `14s` sont en pending)_

**Comment by adriens** [comment]
C'est parfait... maintenant on va coicner sur le temps de download des artefacts (jar, imager docker, ...). j'ai tous les éléments dont j'ai besoin.

> est liée à un état d'attente de Tower "pending" (j'avais déjà signalé) avant le lancement,

Oui, tout à fait, je ne l'ai pas oublié :ok_hand:
