### ISSUE TITLE
Support du paramètre `self_image_url` pour le déploiement Docker 🐳

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/tower-deploy-action#14]
- J'ai du faire une manip sur la GH Action pour pouvoir passer `self_image_url` car les paramètres sont en dur, pour l'instant c'est sur une branche spécifique `docker`
...
_Originally posted by @Dougniel in https://github.com/opt-nc/proxy-docubase/issues/11#issuecomment-1247636881_

**Comment by Dougniel** [comment]
Commits précédents (fait avant qu'il y ait cette issue dédiée): 
189b4da35e8f0827f9409bf214bc62c7c21cd7fc
7535e0c576fa0958070e19157087f34d38e3300b
59089e11f381c05392cde8bfffaf893c3c3890f5
d8d8fc2e86c3bcb0be08a55dfd7125c87889831e

**Comment by Dougniel** [comment]
mince la version n'a pas été déclenché 🫤

**Comment by Dougniel** [comment]
Alors ça passe mais j'ai ça 🤔 :

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/39691264/190616925-bdb6e77a-3fc2-4061-aa54-fbf228934097.png">

**Comment by Dougniel** [comment]
Ah zut j'ai oublié la partie déclaration ! 😅

**Comment by mbarre** [comment]
> mince la version n'a pas été déclenché 🫤
> 
> **MAJ** : normal, la version est manuelle wink

Bien vu, ce serait peut etre bien d'y mettre du semantic release. je me l'ajoute.
