### ISSUE TITLE
🗣️  Publish dedicated DEV.to post 📑 

### ISSUE THREAD

**Issue by adriens** [opt-nc/tower-deploy-action#2]
# ✅ Actions

- [x] Write article @adriens 
- [x] get reviewed by @mbarre 
- [x] Publish on dev.to ( drop the url on this issue) -> @adriens 
- [x] Tweet (& tag `@github` & `@ASFMavenProject`) & drop the tweet url on this issue) -> @adriens 
- [x] Post on linkedIn & drop url on this issue) -> @adriens 
- [x] Post on internal channels on Teams/Culture IT -> @adriens 
- [ ] #9

**Comment by adriens** [comment]
@mbarre I send you the url in DM so you can perform the review process/
🤞 you'll like it 🙏

**Comment by adriens** [comment]
url sent, time to enjoy 😸  @mbarre

**Comment by mbarre** [comment]
Hi Adriens, really good article.  :congratulations: 
Read in 5min.
Just one thing, no review for qualification deployment.

 That's ok for me.

**Comment by adriens** [comment]
Thanks for your very kind feedback, i'm going ahead to the next steps now.

**Comment by adriens** [comment]
here it is : https://dev.to/adriens/speeding-up-time-to-market-with-custom-github-actions-3md0

**Comment by adriens** [comment]
🐦 https://twitter.com/rastadidi/status/1488725031631069186

**Comment by adriens** [comment]
[lnkedIn](https://www.linkedin.com/posts/adrien-sales_speeding-up-time-to-market-with-custom-github-activity-6894492071734996992-X-cT)
