### ISSUE TITLE
Linter le template YAML

### ISSUE THREAD

**Issue by mbarre** [opt-nc/tower-deploy-action#3]

**Comment by adriens** [comment]
Pas hésiter à aller regarder https://github.com/opt-nc/yamlfixer/issues/1 créé par @tamere-allo-peter

**Comment by tamere-allo-peter** [comment]
Oui merci @adriens, commentaires et/ou critiques constructives bienvenues

**Comment by mbarre** [comment]
TODO : En faire une github action et voir comment l'appeler dans la github-action de deploiement

**Comment by tamere-allo-peter** [comment]
@mbarre c'est pas vraiment le but, en tout cas pour moi. _yamlfixer_ est susceptible de modifier ton code YAML, et malheureusement, du fait du fonctionnement de yamllint (qui lui existe déjà en tant qu'action GitHub), peut y introduire des erreurs. Aussi l'utiliser automatiquement au sein d'un workflow en tant qu'action me semble dangereux.

**Comment by adriens** [comment]
Mais il purrait faire une PR sur une branche @tamere-allo-peter ...PR qui elle même suivrait des checks de CI, qu'en penseez-vous ?

**Comment by mbarre** [comment]
ca pourrait etre pas mal la PR

**Comment by adriens** [comment]
> ca pourrait etre pas mal la PR

En mode `yamlllintBOT`

**Comment by mbarre** [comment]
Hello @tamere-allo-peter ,

J'ai bien avancé sur la github action :star:   yamlfixer-action :star: , qui te fait une PR avec les corrections.

J'aurai besoin d'une image docker sur docker hub contenant le script python. Ca me permettra de recuperer tes évol facilement. Est-ce que je peux te faire une PR pour ca ?

Dans ma PR, il y a aura le dockerfile, le workflow qui publie l'image a chaque release et un petit mot dans le README.md.

Dis moi si ok, je te fais la PR.

**Comment by tamere-allo-peter** [comment]
Bin le souci c'est que je suis complètement incapable de répondre à ta demande.
J'ai fait une "initiation" de 2h à Docker il y a deux ans, pas touché depuis, et pas trop le temps actuellement malheureusement :-(

**Comment by mbarre** [comment]
Ca tombe bien tu n'auras rien à faire à part accepter la pull request et faire une release pour que l'image Docker soit publiée :smile:

**Comment by mbarre** [comment]
Ca y est l'image docker est sur Docket hub, merci @tamere-allo-peter 
https://hub.docker.com/r/optnc/yamlfixer

Reste plus qu'a renseigner la page d'accueil, je m'en occupe très vite :)

**Comment by mbarre** [comment]
Github action publiée
https://github.com/marketplace/actions/yaml-fixer

**Comment by adriens** [comment]
WOW !
