### ISSUE TITLE
Add the url to the post to the GH Action homepage and to the GH repo itself -> @mbarre

### ISSUE THREAD

**Issue by adriens** [opt-nc/tower-deploy-action#9]
Here is the target url : https://dev.to/adriens/speeding-up-time-to-market-with-custom-github-actions-3md0

**Comment by adriens** [comment]
The final touch is for you @mbarre 🎆

**Comment by adriens** [comment]
🎆 
![image](https://user-images.githubusercontent.com/5235127/153534264-a53e5746-0603-4678-928a-1a53f87a1e23.png)

**Comment by mbarre** [comment]
ca te convient ?

**Comment by adriens** [comment]
> ca te convient ?

Ben carrément, super l'idée du badge ❣️
